---
title: "hNESCs_polar_Final"
author: "Alise"
modidied: "kinza"
date: "2019 M10 9"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
getwd()
```
```{r}
metdata <- read.csv("hNESCs_polar_GC_MS.csv", header=T, row.names=1, sep="\t")
```


```{r}
library(tidyverse)
library(pheatmap)
library(RColorBrewer)
library(matrixStats)
```

```{r}
data<- metdata %>% mutate(Ctrl_39 = rowMedians(as.matrix(metdata[,1:3])))%>% 
  mutate(Ctrl_48 = rowMedians(as.matrix(metdata[,4:6])))%>%
  mutate(Ctrl_56 = rowMedians(as.matrix(metdata[,7:9])))%>%
  mutate(IPD_12 = rowMedians(as.matrix(metdata[,10:12])))%>%
  mutate(IPD_13 = rowMedians(as.matrix(metdata[,13:15])))%>%
  mutate(IPD_2490 = rowMedians(as.matrix(metdata[,16:18])))%>%
  mutate(IPD_28 = rowMedians(as.matrix(metdata[,19:21])))%>%
  mutate(IPD_30C2 = rowMedians(as.matrix(metdata[,22:24])))%>%
  mutate(IPD_30C9 = rowMedians(as.matrix(metdata[,25:27])))
```
```{r}
data2<-data[,c(28:32, 34)]
```

```{r}
colnames(data2)<-c('CTRL_1', 'CTRL_2', 'CTRL_3', 'IPD_1', 'IPD_2', 'IPD_3')

Z_Normalize<-function(x){return((x-mean(x))/(sd(x)))}

NormalisedData_Zscore = t(apply(as.matrix(data2),1,Z_Normalize))

pheatmap(as.matrix(NormalisedData_Zscore), color = colorRampPalette(rev(brewer.pal(n = 8, name = "Spectral")))(100),legend=TRUE, main="Polar extracellular metabolites", angle_col = 45, fontsize_row = 7, fontsize_col=10,cellwidth = 30, width=30, height = 15)

```
```{r}
Ctrl <- data2[grepl("CTRL", names(data2))]
iPD <- data2[grepl("IPD", names(data2))]
```




###PCA
```{r}
library(factoextra)

tCtrl_iPD <- t(data2)

res.pca <- prcomp(tCtrl_iPD, scale = TRUE)
summary(res.pca)
fviz_eig(res.pca, addlabels = TRUE, ylim = c(0, 70)) ### to see the importance of each component

#eig.val <- get_eigenvalue(res.pca)
#eig.val
```
```{r}
library("corrplot")
var <- get_pca_var(res.pca)
#corrplot(var$cos2, is.corr=FALSE)
#corrplot(var$contrib, is.corr=FALSE)  
fviz_contrib(res.pca, choice = "var", axes = 1, top = 10) ###visualise top 10 contributors/mets to the variance given by 1st dimension
fviz_contrib(res.pca, choice = "var", axes = 2, top = 10) ###visualise top 10 contributors/mets to the variance given by 2nd dimension
#fviz_contrib(res.pca, choice = "var", axes = 1:2, top = 10)
```

```{r}
fviz_pca_ind(res.pca,
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE )    # Avoid text overlapping
```


```{r}
fviz_pca_var(res.pca,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             legend.title = "Contribution",
             repel = TRUE     # Avoid text overlapping
             )
```
```{r}
fviz_pca_biplot(res.pca, repel = TRUE,
                col.var = "#2E9FDF", # Variables color
                col.ind = "#696969"  # Individuals color
                )
```
```{r}
Condition <- as.factor(c(rep("CTRL",3),rep("IPD",3)))
g <- fviz_pca_ind(res.pca, 
             col.ind = Condition, # color by groups
             palette = c("#48B368",  "#FC4E07"),
             addEllipses = TRUE, # Concentration ellipses
             ellipse.type = "confidence",
             legend.title = "Condition",
             geom.ind =  "text",
             labelsize=9,
             repel = TRUE
             )
ggpubr::ggpar(g,
              font.ytickslab = 24, font.xtickslab = 24, font.x = 24, font.y = 24, font.legend = 24, title="")

```


###Ttest with Welchs correction
```{r}
pvalue=sapply(1:nrow(metdata),function(i)
{t.test(Ctrl[i,],iPD[i,])$p.value}
)
FC <- apply(iPD,1,mean)/apply(Ctrl,1,mean)
FDR <- p.adjust(pvalue, method = "BH")

CtrlvsiPD = cbind(FC, pvalue, FDR) 
#write.csv(CtrlvsiPD,file="Ttest.csv")

CtrlvsiPD<-data.frame(CtrlvsiPD)
Significance<-CtrlvsiPD[with(CtrlvsiPD,order(pvalue)),]
head(Significance)
#write.csv(Significance, 'Ttest_hNESCs_Polar.csv')

```
```{r}
library(ggplot2)
tCtrl_iPD %>% as_tibble(tCtrl_iPD, rownames='Labels') %>%
  mutate(Condition = case_when(str_detect(Labels, 'IPD') ~ 'IPD', str_detect(Labels, 'CTRL') ~ 'CTRL',
                             TRUE ~ 'test'))  -> metdataT
```


```{r}
###Pyridine-2,3-dicarboxylic acid
my_sum <- metdataT %>%
  group_by(Condition) %>%
  summarise( 
    n=n(),
    mean=mean(Pyridinedicarboxylic_acid),
    sd=sd(Pyridinedicarboxylic_acid)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))

t.test(Pyridinedicarboxylic_acid~Condition, data=metdataT)

ggplot(my_sum) +
    geom_bar(aes(x = Condition, y = mean, fill=Condition), stat="identity",alpha=1, width = 0.6) +
  scale_fill_manual(values=c('dark grey', 'grey38'))+
    geom_errorbar( aes(x = Condition, ymin = mean-sd, ymax=mean+sd), width=0.1, colour="black", alpha=0.9, size=1.3)+
  theme_classic()+
    labs(title="Pyridine-2,3-dicarboxylic acid", y = "Relative abundance")+
    theme(plot.title=element_text(size=32, face="bold", hjust = 0.1),
        axis.text.x=element_text(size = 30, face = "bold"), 
        axis.title.x=element_blank(), axis.title.y=element_text(size=34),axis.text.y=element_text(size=30), legend.text = element_text(size=30), legend.title = element_text(size=30))
```


```{r}
###creating a Volcano plot

df <- as.data.frame(CtrlvsiPD)
df1 <- as.data.frame(log(df$FC,2))
df2 <- as.data.frame(-log(df$FDR,10))


mets <- rownames(CtrlvsiPD)
data <- cbind.data.frame(mets,df,df1)
colnames(data) <- c("mets","FC", "pvalue", "FDR", "log2FC")

```


```{r}
library(ggrepel)
data$Significant <- ifelse(data$pvalue < 0.05, "pvalue < 0.05", "Not significant")
ggplot(data, aes(x = log2FC, y = -log10(pvalue))) +
  geom_point(aes(color = Significant), size=4) +
  scale_color_manual(values = c("black", "red")) +
    labs( x = "log2FoldChange")+
  theme_bw(base_size = 12) + theme(legend.position = c(0.1,0.85), legend.title = element_blank(), axis.text.x=element_text(size = 14), 
axis.title.y=element_text(size=13), legend.text=element_text(size=12)) +
  geom_text_repel(
    data = subset(data, pvalue < 0.05),
    aes(label = mets),
    size = 5,
    box.padding = unit(0.35, "lines"),
    point.padding = unit(0.3, "lines")
  )
```
```{r}
data$Significant <- ifelse(data$pvalue < 0.05, "pvalue < 0.05", "Not significant")
ggplot(data, aes(x = log2FC, y = -log10(pvalue))) +
  geom_point(aes(color = Significant), size=4) +
  scale_color_manual(values = c("black", "red")) +
    labs( x = "log2FoldChange")+
  theme_bw(base_size = 20) + theme(legend.position = c(0.75,0.85), legend.title = element_blank(), axis.title.x=element_text(size = 28), 
axis.title.y=element_text(size=28), legend.text=element_text(size=24), text=element_text(size=34))
  
  
```

```{r}
write.table(data2, file = "polar_metab.tsv", quote = F, sep = "\t", row.names = T, col.names = T)

```


