# Two classes comparison
# DAcomp(): perform differential activation comparisons of nodes, pathways and functions at the same time
# This function conducts a comparison of the nodes, paths, and functional activation matrices within the output object 
# generated by the metabopathia() / hipathia() function.
# The test used for the comparison of each activation matrix can be set through parameters path.method, node.method and function.method.
# Options include:
#   - *wilcoxon* , in which case a two groups comparison will be applied: coin::wilcoxsign_test for paired data and stats::wilcox.test for unpaired 
#   - or *limma*, in which case functions lmFit(), contrasts.fit() and eBayes() from the limma package will be used.
# By default,
# - node.method is set to limma 
# - and path.method and function.method, set to wilcoxon.

## Parameters
# - `paired`: A boolean value indicating whether samples are paired (FALSE by default).
# - `order`: A boolean value indicating whether the results should be ordered by p.value (FALSE by default).
# - `adjust`: A boolean value indicating whether the p.values should be adjusted by the p.adjust() function using the FDR method (TRUE by default).
# - `conf.level`: Indicates the confidence level if `adjust` is set to TRUE.

compare_pipeline <- function(metdata, groups, expdes, g2 = NULL,
                             path.method = "wilcoxon", node.method = "limma", fun.method = "wilcoxon",
                             order = FALSE, paired = FALSE, adjust = TRUE, conf.level = 0.05, sel_assay = 1){
  # rowData(metdata[["paths"]])
  # this is directl from Doku
  # Perform comparisons
  # metdata groups has a cols colData instead of group : colData(metdata[["nodes"]]) : DataFrame with 12 rows and 1 column: cols
  DAdata <- hipathia::DAcomp(hidata = metdata, groups = groups , expdes = expdes, g2 = g2,
                             path.method = path.method, node.method = node.method, fun.method = fun.method,order = order,
                             paired = paired, adjust = adjust, conf.level = conf.level, sel_assay = sel_assay)
  return(DAdata)
}


    