# Two classes comparison and overlay metabolic concentration 
# DAcomp(): perform differential activation comparisons of nodes, pathways and functions at the same time
# This function conducts a comparison of the nodes, paths, and functional activation matrices within the output object 
# generated by the metabopathia() / hipathia() function.
# The test used for the comparison of each activation matrix can be set through parameters path.method, node.method and function.method.
# Options include:
#   - *wilcoxon* , in which case a two groups comparison will be applied,
#   - or *limma*, in which case functions lmFit(), contrasts.fit() and eBayes() from the limma package will be used.
# By default,
# - node.method is set to limma 
# - and path.method and function.method, set to wilcoxon.

## Parameters
# - `paired`: A boolean value indicating whether samples are paired (FALSE by default).
# - `order`: A boolean value indicating whether the results should be ordered by p.value (FALSE by default).
# - `adjust`: A boolean value indicating whether the p.values should be adjusted by the p.adjust() function using the FDR method (TRUE by default).
# - `conf.level`: Indicates the confidence level if `adjust` is set to TRUE.

compare_pipeline_overlaying <- function(metdata, metabo_vals, groups, expdes, g2 = NULL,
                             path.method = "wilcoxon", node.method = "limma", fun.method = "wilcoxon",
                             order = FALSE, paired = FALSE, adjust = TRUE, conf.level = 0.05, sel_assay = 1){
  # rowData(metdata[["paths"]])
  # this is directl from Doku
  # Perform comparisons
  # metdata groups has a cols colData instead of group : colData(metdata[["nodes"]]) : DataFrame with 12 rows and 1 column: cols
  # $shape =="circle"
  # metabo_vals_annotated <- from_KeggID_2_NodeIDs(metabo_vals, pathways) # has to return same matrix but duplicating node if needed with node id used in the pathways
  KeggID_2_NodeIDs <-do.call(rbind,lapply(pathways$pathigraphs,function(ig){
    ig <- ig$graph
    nodeID <- V(ig)$name
    KeggID <- str_extract(V(ig)$tooltip, "(?<=href=http://www.kegg.jp/dbget-bin/www_bget\\?)[^>]+")
    return(tibble(nodeID=nodeID,KeggID=KeggID))
    }
  )) %>% filter(!is.na(KeggID)) 
  # %>% filter(KeggID %in% rownames(metabo_vals))
  
  metabo_vals_annotated <- metabo_vals %>% as.data.frame() %>% mutate(KeggID = rownames(.)) %>%  left_join(KeggID_2_NodeIDs) %>% 
      filter(!is.na(nodeID))
  rownames(metabo_vals_annotated)<-metabo_vals_annotated$nodeID
  metabo_vals_annotated<- metabo_vals_annotated %>% select(-nodeID,-KeggID)
  if(!all(colnames(assay(metdata[["nodes"]])) %in%colnames(metabo_vals_annotated))){
    stop("not all samples of exp matrix are in metabolomics data!")
  }
  assay(metdata[["nodes"]], withDimnames = F) <- assay(metdata[["nodes"]]) %>% as.data.frame() %>%
    filter(!row.names(.) %in% rownames(metabo_vals_annotated)) %>% # and all the row is 1
    bind_rows(metabo_vals_annotated) %>% as.matrix()

  DAdata <- DAcomp(hidata = metdata, groups = groups , expdes = expdes, g2 = g2,
                             path.method = path.method, node.method = node.method, fun.method = fun.method,order = order,
                             paired = paired, adjust = adjust, conf.level = conf.level, sel_assay = sel_assay)
  return(DAdata)
}